name: Run Script
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas requests playwright tqdm pymongo dnspython certifi orjson

      - name: Install Playwright browsers
        run: playwright install chromium --with-deps

      - name: Run script
        env:
          BASE_DIR: ${{ secrets.BASE_DIR }}
          TOKEN: ${{ secrets.TOKEN }}
        run: python main.py
